### ISSUE TITLE
Birthday registration.

### ISSUE THREAD

**Issue by stepheljobs** [stepheljobs/blaziken#1]
Improper set of birthdate (Birthdate validation) example february 29 , 30, 31 .
1905 - 2016

![image](https://cloud.githubusercontent.com/assets/8773383/12390598/7a2dfbe0-be1c-11e5-9b18-3f66ab9c8195.png)

**Comment by jmong143** [comment]
birthdate text hide after selecting

**Comment by stepheljobs** [comment]
Birthday is not indicated in birthday form, users might be confused about this certain input fields.

![screen shot 2016-01-21 at 8 35 19 am](https://cloud.githubusercontent.com/assets/8773383/12467718/ab72de3e-c018-11e5-8b5c-7b582c9147a7.png)

My Suggestion:

Change the placeholder to "Birthday"
Adjust the .input-daterange input from center to left.
Add font size to 15px.

Check this screenshot as reference:
![screen shot 2016-01-21 at 8 38 13 am](https://cloud.githubusercontent.com/assets/8773383/12467754/0ac2d574-c019-11e5-9254-e6219b05cf2b.png)

**Comment by jmong143** [comment]
aligning "Birthday" text in left
and change font of input-daterange to 15px


![1](https://cloud.githubusercontent.com/assets/13063423/12474047/b7df0096-c052-11e5-88ac-a53ef67d44b0.jpg)

**Comment by stepheljobs** [comment]
QA and fixed. closing now.
