### ISSUE TITLE
Concurrent facebook login

### ISSUE THREAD

**Issue by stepheljobs** [stepheljobs/blaziken#11]
Concurrent facebook login

**Comment by jmong143** [comment]
sir i'm done with the facebook login and signup..
in my localhost it works ..and the oauth configuration is now working ..

when the user click "login with facebook" or "signup with facebook" it will lauch this page

![fb login](https://cloud.githubusercontent.com/assets/13063423/12475177/ef844160-c05b-11e5-9579-2beeb8813b0e.jpg)

after that if the user is not logged in, the permission of the app will appear like this

![fb login 2](https://cloud.githubusercontent.com/assets/13063423/12475226/6624d136-c05c-11e5-8d8d-f119b86c8ec9.jpg)


then it will proceed to the users/dashboard

**Comment by stepheljobs** [comment]
Not working on my samsung android. will test this again to other device.

**Comment by stepheljobs** [comment]
Fixed and closing.
