### ISSUE TITLE
Last message not cleared

### ISSUE THREAD

**Issue by stepheljobs** [stepheljobs/blaziken#17]
Minor Bugs: The message of a sender also appeared on reply message textbox -grabs
Screenshot
https://drive.google.com/file/d/0B5i4zDCP43_oRHE1bWJwNEo4Rzg/view?usp=sharing

**Comment by jmong143** [comment]
fix for clearing last message

my sample message:
![17](https://cloud.githubusercontent.com/assets/13063423/12395578/699e9322-be3d-11e5-9d9b-d4a21a21b568.jpg)

after sending (click for "send a message" modal textbox will be clear)
![17p1](https://cloud.githubusercontent.com/assets/13063423/12395596/90683e40-be3d-11e5-8319-43b63982b161.jpg)

**Comment by stepheljobs** [comment]
QA and fixed, closing this issue now.
