### ISSUE TITLE
Update profile notification.

### ISSUE THREAD

**Issue by stepheljobs** [stepheljobs/blaziken#19]
No popup notification in update profile after editing-- mira https://drive.google.com/open?id=0B0FUsG3AF5KkWDdMdUFjMFltNWM

**Comment by jmong143** [comment]
already done and commited under issue #20 

![19](https://cloud.githubusercontent.com/assets/13063423/12413007/79de1f62-bec6-11e5-94ce-a1f256ad248c.jpg)

**Comment by stepheljobs** [comment]
@jmong143 would it be good if we remove the password field? baka kasi ma mistaken nila yung forgot password sa update password? What do you think?

![screen shot 2016-01-23 at 8 56 40 am](https://cloud.githubusercontent.com/assets/8773383/12526908/eab3c5ea-c1ad-11e5-943d-8e93cbcdad27.png)

**Comment by stepheljobs** [comment]
This issue is already fixed btw.

**Comment by stepheljobs** [comment]
Sorry my mistake those password inputs pala is to confirm the profile update user. its a validation not a field to update the password. this is now fix and will be close. lets add more design and ux for this page next week.
