### ISSUE TITLE
Edit profile, Birthday Reset.

### ISSUE THREAD

**Issue by stepheljobs** [stepheljobs/blaziken#20]
in selecting EDIT PROFILE, birthdate reset -- mira https://drive.google.com/open?id=0B0FUsG3AF5KkbEltQXJhTnA2aDg

**Comment by stepheljobs** [comment]
Profile display, transfer to dashboard.

**Comment by jmong143** [comment]
changing birthdate selection to date picker then birthdate is displaying according to database

![20p1](https://cloud.githubusercontent.com/assets/13063423/12394706/7f330e8e-be38-11e5-8bc7-27413b279f1c.jpg)


update users profile code is functioning

![20](https://cloud.githubusercontent.com/assets/13063423/12395156/0db6cfd6-be3b-11e5-9fcd-25f9fac3d26f.jpg)

**Comment by stepheljobs** [comment]
QA and fixed, but lets add better design and ux for this page mike next week.
