### ISSUE TITLE
Image icon with text (upload image here) --mira

### ISSUE THREAD

**Issue by stepheljobs** [stepheljobs/blaziken#21]
Image icon with text (upload image here) --mira

**Comment by stepheljobs** [comment]
Improve text spiel and add icon.

![screen shot 2016-01-18 at 10 03 19 pm](https://cloud.githubusercontent.com/assets/8773383/12392984/ddcbd4f4-be2d-11e5-92ce-b317f79883da.png)

**Comment by jmong143** [comment]
I add text like "upload your images here" just like the dropzone text in version 1

![21](https://cloud.githubusercontent.com/assets/13063423/12411189/6376bd06-beb7-11e5-93e5-98883b1373ce.jpg)

**Comment by stepheljobs** [comment]
@jmong143 can we removed the "Drop files here to upload" also? What do you think?

**Comment by stepheljobs** [comment]
you can also check this link for reference how to remove that line. http://www.dropzonejs.com/#config-dictDefaultMessage

**Comment by jmong143** [comment]
done for custom text in dropzone

![21p1](https://cloud.githubusercontent.com/assets/13063423/12473863/05bd0fa8-c051-11e5-9dee-b44ed270220b.jpg)

**Comment by stepheljobs** [comment]
QA and fixed, closing this issue now.
