### ISSUE TITLE
There is no Date when the product uploaded - Mond

### ISSUE THREAD

**Issue by stepheljobs** [stepheljobs/blaziken#26]
There is no Date when the product uploaded - Mond

**Comment by stepheljobs** [comment]
Lets add something like momentjs for the item soon.

![screen shot 2016-01-18 at 9 23 23 pm](https://cloud.githubusercontent.com/assets/8773383/12392220/52442fc6-be28-11e5-889d-968d195fd932.png)

**Comment by stepheljobs** [comment]
![screen shot 2016-01-18 at 9 41 40 pm](https://cloud.githubusercontent.com/assets/8773383/12392536/e284e150-be2a-11e5-8c69-1c06c833fdae.png)

**Comment by anthonyteoxon** [comment]
Done in adding moment(formatted time), but not in design.

**Comment by stepheljobs** [comment]
QA and fixed.

**Comment by stepheljobs** [comment]
Duplicated at issue #29
