### ISSUE TITLE
No Message how long the product posted? Ex. Posted: 3 days ago - Mond

### ISSUE THREAD

**Issue by stepheljobs** [stepheljobs/blaziken#29]
No Message how long the product posted? Ex. Posted: 3 days ago - Mond

**Comment by stepheljobs** [comment]
Suggested library: http://momentjs.com/
not sure kung fit to para magamit.

**Comment by anthonyteoxon** [comment]
Done. I used moments.js

**Comment by stepheljobs** [comment]
QA and fixed.
