### ISSUE TITLE
Clickable image.

### ISSUE THREAD

**Issue by stepheljobs** [stepheljobs/blaziken#30]
clickable image, underlined product name when cursor was pointed --mira https://drive.google.com/open?id=0B0FUsG3AF5KkaEtmeWREek1nMGc

**Comment by stepheljobs** [comment]
pwede din highlight or shadow background kapag naghover sa item. like this.
![screen shot 2016-01-18 at 8 49 26 pm](https://cloud.githubusercontent.com/assets/8773383/12391555/922895c8-be23-11e5-90e9-43f1e7e32de1.png)

**Comment by stepheljobs** [comment]
can we add border shadow nalang if hover?

**Comment by jmong143** [comment]
done for adding hover in each products/items according to category

![30p2](https://cloud.githubusercontent.com/assets/13063423/12412573/a5c10e7c-bec2-11e5-8bde-7d8e5bac9fbe.jpg)

**Comment by stepheljobs** [comment]
QA and fixed.
