### ISSUE TITLE
Not available photos

### ISSUE THREAD

**Issue by stepheljobs** [stepheljobs/blaziken#31]
Enhancement: Create default image with "Photos not available" text. this is for some post without images.

**Comment by stepheljobs** [comment]
@jmong143 mike pa attach naman dito yung ginawang design for unavailable photo.

**Comment by jmong143** [comment]
image not available photo

![not available](https://cloud.githubusercontent.com/assets/13063423/12391419/97acf6e8-be22-11e5-8545-85d3465779cc.jpg)

**Comment by stepheljobs** [comment]
Thanks @jmong143

**Comment by stepheljobs** [comment]
Done.

**Comment by stepheljobs** [comment]
This is related with
