### ISSUE TITLE
Cancel button with 11111

### ISSUE THREAD

**Issue by stepheljobs** [stepheljobs/blaziken#32]
Steps to replicate:
1. Login to your account.
2. Click the create post.
3. See the cancel button.

Wrong text spiel for cancel button on create post message.

![screen shot 2016-01-18 at 9 11 19 pm](https://cloud.githubusercontent.com/assets/8773383/12392018/cda4d38e-be26-11e5-9c25-f88c9e5fd98e.png)

**Comment by jmong143** [comment]
done commiting this issue

![32](https://cloud.githubusercontent.com/assets/13063423/12392178/fde77b4a-be27-11e5-8ddb-5e73e6ed8c94.jpg)

**Comment by stepheljobs** [comment]
@jmong143 Images not cleared upon click "cancel button"

Steps to replicate:
1. Fillup the form.
2. Upload image
3. click cancel button.

Notice that the images is not cleared, is this possible to clear?

**Comment by jmong143** [comment]
done for clicking cancel button that dropozone box will empty

**Comment by stepheljobs** [comment]
QA and fixed, closing this issue now.
