### ISSUE TITLE
Prize Range in creating post

### ISSUE THREAD

**Issue by jmong143** [stepheljobs/blaziken#35]
prize range example "1000 - 4000"

![price](https://cloud.githubusercontent.com/assets/13063423/12441824/0406b4b4-bf86-11e5-861e-95abe13132bc.jpg)

**Comment by stepheljobs** [comment]
How does it work mike? I'm trying to test it last night.

**Comment by jmong143** [comment]
sir mond suggest last time if the price textbox have a range just like the example image bellow
i think i'll add some regex in the validation like " - " ?

![35p1](https://cloud.githubusercontent.com/assets/13063423/12472788/b3d414de-c046-11e5-9632-e298567d67d9.jpg)

**Comment by jmong143** [comment]
done for price range by adding regex to enable "space and dash " in validation

![35p2](https://cloud.githubusercontent.com/assets/13063423/12473522/e7eb65e0-c04d-11e5-81cd-957b8c53c77a.jpg)

**Comment by stepheljobs** [comment]
Will not add this feature yet mike.
