### ISSUE TITLE
Details button on item page is not working.

### ISSUE THREAD

**Issue by stepheljobs** [stepheljobs/blaziken#36]
Steps to replicate:
1. Go to any item.
2. Click the "Details" button on the seller info.

![screen shot 2016-01-21 at 8 31 51 am](https://cloud.githubusercontent.com/assets/8773383/12467663/17bd8efa-c018-11e5-81e7-7d6419ae00b8.png)

**Comment by jmong143** [comment]
details button fixed..the problem is when the birthdate is empty ..the .toGMTString getting error because the code expecting for birthdate..so i use if else statement using underscore in index.html

**Comment by stepheljobs** [comment]
QA and fixed, closing this issue now.
