### ISSUE TITLE
in viewing post all address are the same " #123 Highest Bldg. Ortigas, Pasig City, Philippines"

### ISSUE THREAD

**Issue by jmong143** [stepheljobs/blaziken#38]
![address](https://cloud.githubusercontent.com/assets/13063423/12546858/ad4b2028-c387-11e5-8807-a61e5ecf9fe2.jpg)

**Comment by jmong143** [comment]
done for removing address text in viewing post

![removing address](https://cloud.githubusercontent.com/assets/13063423/12546950/2392b430-c388-11e5-8a12-3ad85fd078de.jpg)

**Comment by jmong143** [comment]
done for displaying users address in viewing post

![38p1](https://cloud.githubusercontent.com/assets/13063423/12573526/258f85ee-c435-11e5-9d67-331f3bc68b0e.jpg)

**Comment by stepheljobs** [comment]
Done QA and Fixed already. Closing this issue.
