### ISSUE TITLE
UI: Category bar is not visible.

### ISSUE THREAD

**Issue by stepheljobs** [stepheljobs/blaziken#6]
Android UI, Category bar are hidden after select a chosen category - grabs
![12](https://cloud.githubusercontent.com/assets/8773383/12390821/4acf7dea-be1e-11e5-9b8f-b10a12fc9dd8.jpg)

**Comment by jmong143** [comment]
add category modal in mobile view

![6](https://cloud.githubusercontent.com/assets/13063423/12411476/168e3a84-beba-11e5-89c8-057a447e6b1f.jpg)

**Comment by stepheljobs** [comment]
QA and fixed, closing this issue now.
