### ISSUE TITLE
Item page seller info details button.

### ISSUE THREAD

**Issue by stepheljobs** [stepheljobs/blaziken#8]
Sellers info details button link redirect (need po kasi i refresh)

**Comment by jmong143** [comment]
already function when clicking the navbar

![8](https://cloud.githubusercontent.com/assets/13063423/12399291/10f3307c-be54-11e5-8090-f4a8d0be8480.jpg)

after click users/profile route will display

![8p1](https://cloud.githubusercontent.com/assets/13063423/12399306/1facb7b4-be54-11e5-80c6-a64aeed1d501.jpg)
